### ISSUE TITLE
Logo Design For Mundraub Android

### ISSUE THREAD

**Issue by zularizal** [niccokunzmann/mundraub-android#101]
Hi @niccokunzmann , I'm a graphic designer. I have reviewed your project. You don't have a logo and icon on your application. Therefore I want to make a logo for your project and it's free.

**Comment by niccokunzmann** [comment]
@zularizal Thank you very much for bringing up this issue and offering your time. Just today, I talked to Kai from Mundraub #21 (I forgot to fill this in). They have a logo, the apple with the mask https://mundraub.org/
They like the app and we will converse about what the app needs so they give their trademark for it. 

Since you are a graphic designer, you will surely evaluate if this is suitable for the app.
Do you think it needs adaptation for the app?

However, I am not sure how to embed it into the app. There might be resolution problems.
You are free to create a pull request to improve the app.

Now that I told you this, what are your thoughts?

**Comment by niccokunzmann** [comment]
From your GitHub profile, I conclude, you have some experience. This is my first app.

**Comment by zularizal** [comment]
You have made a good application, in my opinion, you have to improve your application. Here are some of my suggestions for your application:
- Improve the navigation display
- Adjust colors with the website. Maybe the green color matches this application.

**Comment by zularizal** [comment]
I think the logo looks good. In the application you only need to set the navigation (User Interface) to be better.

Sorry, I'm not good at Android. If I could, I would send you pr and improve the look of the application.

**Comment by niccokunzmann** [comment]
@zularizal If you still like to create a logo, you can do that. I would like to name the app fruit radar because now, one can walk around offline and get notification about edible plants nearby.

**Comment by zularizal** [comment]
Hi @niccokunzmann , Do you want a logo like on the mundraub.org site?
or a new logo?

**Comment by niccokunzmann** [comment]
If you have a look at the icons of 
- https://na-ovoce.cz/web/
- https://mundraub.org/
- https://fallingfruit.org/data?c=forager%2Cfreegan&locale=en

They all contain fruit. So, I would say, using a fruit will show the closeness to them.

If you like, you can do something with a radar or not.
Now, there is a loading screen. If you add a radar and this is SVG, one can let the radar rotate when the app loads.

I can imagine that a radar and a fruit do not fit into a small version of the icon. Then, it is up to you what you think is best. Any logo is better than none.
You also know my thoughts about a logo and we can talk back and forth. I see this more as a community project and your contribution is welcome!

**Comment by zularizal** [comment]
Does this design my logo for you?
What do you think?

![bitmap](https://user-images.githubusercontent.com/38547278/46723309-b8618580-cca1-11e8-8ac3-0c8800d28a9c.png)

**Comment by niccokunzmann** [comment]
Awesome! There is a [images folder](https://github.com/niccokunzmann/mundraub-android/tree/master/images/app) would you like to place them in a sub-folder for the logo?

**Comment by niccokunzmann** [comment]
Do you have ideas on when to use black and white and when to use the colored version? If so, we should have a README.md file describing this so it is used consistently.

**Comment by zularizal** [comment]
Full color positive colors (blue and orange) are used for media applications with bright or white backgrounds. Like the logo header, web icon, launcher icon and etc.

The color one color reverse (white) is used for media applications with a background of color or dark-colored photos. Like the status bar and etc.

**Comment by zularizal** [comment]
Of course, I will put it.
Before that, do you want me to put the logo into an icon? Or use it like that?

**Comment by niccokunzmann** [comment]
The raw images are useful, and I like it if you add them to the images folder. This gives others the freedom to adapt them e.i. low resolution ones, ... I do not know what the future will bring.

About the icon: I saw something like this in Android Studio. Currently, I do not know what it takes to make an icon suitable for an app.

**Comment by zularizal** [comment]
Yes, I will put this logo with the .svg file format.

This is the icon that I mean.
You can use this on the launcher icon on your application.
What do you think?

![bi](https://user-images.githubusercontent.com/38547278/46728141-59553e00-ccac-11e8-812b-568c6f388bad.png)

**Comment by niccokunzmann** [comment]
I like it :)

**Comment by zularizal** [comment]
I have added RAW images and a new icon for your project. #190 

And also I have uploaded the new logo and icon of this project to drive. Check this https://drive.google.com/open?id=10NDl3BLmoRc4mZcEXew7WsLJM2kKAWc3

**Comment by niccokunzmann** [comment]
@zularizal Since you opened the issue, are you satisfied with the current status and would you like to close it?

**Comment by zularizal** [comment]
I just want to help you. If there is something you want to need about design, then let me know. I will help you.

I will close this issue. Hopefully your app can run better in the future.

**Comment by niccokunzmann** [comment]
@zularizal Since your icon is added, there are four more people who like to work on the app. I am happy to get to know them. I tag issues as "visual" issues if not much coding is required. However, I understand design is much more. I do not know when to ask for help as I do not think I would even recognize the design mistakes. I will surely recognize anything that is a little off in code as I am trained in that.

If you like, you can walk though the app and write issues about where to improve the design. I can then contribute details on how to change the source code to achieve this change. This will make useful issues for new contributors.
