### ISSUE TITLE
Do not save plants with only default entries

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/mundraub-android#34]
If a plant was not edited, just has the fields from the start
- delete this plant when the new plant activity is closed
- stop GPS position updates on the plant as they are no use

**Comment by Marky25** [comment]
Hi Nicco, as this issue is open, I would try to fix it.

If I understand this correctly, when user wants to save new plant, but with no change of its data, the plant should be deleted from collection as well as the location updates should be disabled on this plant ?

Thank's for your reply and cheers :-)

**Comment by niccokunzmann** [comment]
@Marky25 Yes, this is correct!

**Comment by Marky25** [comment]
Okay, great ;-)
I'll drop questions here if needed and create pull-request when done.
I'm a newbie at GitHub, so let's see what we can do here :-D

**Comment by Marky25** [comment]
Hi Nicco,
I've come with a solution for this issue and hope that it is what you've expected :-D
And there is one more thing I have in mind which came out during development.
It will be nice, if user gets feedback (in form of short message), that his plant was not saved.
Probably, this can be done in another issue. What do you think ? :-)
