### ISSUE TITLE
show map of plants

### ISSUE THREAD

**Issue by tbdal** [niccokunzmann/mundraub-android#75]
app shows a blank screen and no login after start
Platform: Sony z5 sumire with lineageos 14.1 (build 180825)

![screenshot_20180829-160951](https://user-images.githubusercontent.com/6881189/44793526-c0a8aa00-aba6-11e8-89e5-f160331d2d70.png)

from log:
System.err
	at eu.quelltext.mundraub.common.Helper.saveUrlToFile(Helper.java:56)
System.err
	at eu.quelltext.mundraub.map.MapCache$Task.doInBackground(MapCache.java:129)
System.err
	at eu.quelltext.mundraub.map.MapCache$Task.doInBackground(MapCache.java:106)

**Comment by niccokunzmann** [comment]
Thanks for reporting!
That is correct in my view. The app has no plants as you did not record one. If you press the + button, a dialog should open so that you can record a plant. I think, this is a usual Developer + First Timer User issue: I am too much into the development that I can hardly understand what your ideas are.

My question to improve this is:
What do you expect? What would you like the app to tell you and how?

**Comment by Michele64** [comment]
from the point of view of an user I would expect a map of my surroundings and a log in form

**Comment by niccokunzmann** [comment]
What would the purpose of the map be? Would it be to find plants?
Would the map also include markers of plants if there are some?

**Comment by Michele64** [comment]
well yes, that's the whole point of the website, to share and find plants and fruits

**Comment by niccokunzmann** [comment]
:smile:  Oh. Yes. I focused on the sharing part: currently, one can only share plants.

If you like, you can help me. There are some ideas I have how to help me:

- Feature description: In order to get the feature implemented, describe it and later rate it.
  please add a description about the map, what you see, how it behaves.
  - You can have wild ideas, best separated from each other by bullet points (I also have some ideas as I like that feature, but maybe different from how you like it)
  - Then, we can extract the essence, create new issues and tackle that.
- Research:
  - Are there already apps for offline usage which have those features you talk about?
    - Is it possible to just pass the plants to them and they do the rest?
    - If not, this feature is needed for so many finder-apps: a map, markers, positioning, it is all common to them. Please list those apps, so we can cooperate using free software or just extract the code.

**Comment by tbdal** [comment]
sure, i'd love to see:
- interactive map with 
      *possibility to show mundraub entries 
      *based on osm-data, only based on foss-frameworks&data-sources 
      *if entry is clicked details will be shown in pop-up/separate view
      *possibility to show current gps-position on map
      (*possibility to edit entry on click, optional)

**Comment by niccokunzmann** [comment]
So, I thought about it and this are ways for going forward with the implementation.
I you have thoughts about this, let me know, also if you like to do part of it.

- [ ] show a map similar to when the position is edited on the map  
    ![](https://github.com/niccokunzmann/mundraub-android/raw/master/fastlane/metadata/android/en/phoneScreenshots/locate-plant-1.png)
    - [ ] add plants to the map
        - [ ] query Mundraub for this https://mundraub.org/cluster/plant?bbox=13.049526214599611,50.674052824784184,13.185911178588869,50.68917180712749&zoom=14&cat=4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37
        - [ ] use the markers with colors from mundraub.org
    - [ ] if entry is clicked details will be shown in pop-up/separate view
        - [ ] we can view the type of the plant as the type is given in the query result
        - [ ] we can view the plant in the web browser
    - [ ] possibility to show current gps-position on map

**Comment by niccokunzmann** [comment]
If you like to help me resolve this, #79 adds the images which we need to get from Mundraub.org.

**Comment by niccokunzmann** [comment]
@tbdal @Michele64 Thanks for your input. Now, I progressed on this issue. In a new release, you should be able to view the existing plants on the map when you click the map of a plant you added.

I would like to know the following:

- When would you like to see the map? What do you do so the map opens? "E.g. when the app opens, the first thing I would like to see is the map of plants from Mundraub.org." or do you like to reach it via the menu? You can create a new issue for discussion as this issue is already too filled in my opinion to be a good starting point for others who like to discuss this. 

- > *if entry is clicked details will be shown in pop-up/separate view
  > *possibility to show current gps-position on map
  > (*possibility to edit entry on click, optional)
  
  These can be explained more. Please create new issues for them.

**Comment by niccokunzmann** [comment]
I am fine with the app right now as I can see plants on the map when I upload to not upload any duplicates.
I will work more on the app when I think it is time to take it off-line to find plants when walking around.
If you like to see something more happen in your favor, please comment or start contributing e.g. with #79.

**Comment by niccokunzmann** [comment]
I will close this now and wait for further input. I know it is not 100% done. You will do me a favor if you add small new issues so I can choose and others can come in and have a clear purpose to support.
